defaults:
    - _self_
    - override hydra/hydra_logging: none
    - override hydra/job_logging: none

checkpoint: ./checkpoint/csac-${setting.task_name}-${setting.dataset_name}
device: gpu
seed: 0

setting:
    task_name: walk
    dataset_name: medium
    state_dims: 24
    action_dims: 6

parameter:
    num_layers: 3
    hidden_dims: 256
    actor_lr: 3e-4
    critic_lr: 3e-4
    discount_factor: 0.99
    update_rate: 5e-3
    num_samples: 10
    penalty_weight: 5.0

strategy:
    num_epochs: 1000
    warmup_epochs: 0
    batch_size: 256
    eval_interval: 10
    sample_episodes: 5

hydra:
    run:
        dir: ${checkpoint}
    sweep:
        dir: ${checkpoint}
