defaults:
    - _self_
    - override hydra/hydra_logging: none
    - override hydra/job_logging: none

checkpoint: ./checkpoint/rsp-${setting.task_name}-${setting.dataset_name}
device: gpu
seed: 0

setting:
    task_name: walk
    dataset_name: medium
    state_dims: 24
    action_dims: 6

strategy:
    sample_episodes: 5

hydra:
    run:
        dir: ${checkpoint}
    sweep:
        dir: ${checkpoint}
